### ISSUE TITLE
Talk about initiitives with Wake County at Meeting

### ISSUE THREAD

**Issue by ChrisTheDBA** [codeforraleigh/Captains-Task-List#147]
We've got more than a few people wanting to talk projects so I think we need to discuss the project we've discussed with Bill G and team.

**Comment by jhibbets** [comment]
When do you want to try and do this? I could maybe meet this Friday. I head to ATX on Saturday. Back on Wednesday.

**Comment by ChrisTheDBA** [comment]
I can do Friday. I have one meeting @ 10:30. It's a phone call. Open otherwise.

We are meeting w/ Greeves on Thursday and I'll see if he's done any of the connections with business unit(s).
