### ISSUE TITLE
Onboard new members from 3/27 meet-up

### ISSUE THREAD

**Issue by jhibbets** [codeforraleigh/Captains-Task-List#156]

**Comment by ChrisTheDBA** [comment]
What do you need me to do?

Chris Mathews

**Comment by jhibbets** [comment]
I got it. Just need to carve out some time today.

**Comment by jhibbets** [comment]
New members requesting access to Google Drive have been added

**Comment by jhibbets** [comment]
New members requesting they be added to our newsletter have been subscribed

**Comment by jhibbets** [comment]
New members request access to Code for Raleigh GitHub have been added

**Comment by jhibbets** [comment]
New members who wanted an invite to code for NC slack have been invited

**Comment by jhibbets** [comment]
I emailed civic whitaker with new members who wanted to be added to CfA slack
