### ISSUE TITLE
Final review 2016 prospectus (Chris)

### ISSUE THREAD

**Issue by jhibbets** [codeforraleigh/Captains-Task-List#57]

**Comment by ChrisTheDBA** [comment]
I like the level of detail.  In the past, I've always used those as talking points to start the conversation. So I might add the phrasing for "some of the benefits could include" but keep it open.

Also do we need to distinguish between sponsorship vs donation vs in-kind. Sponsorship comes with expected benefits while donations come with little or none. It's also for a lot of companies where the money comes from. Sponsorship is usually marketting/promotion and donation is charitable - like Red Hat or Rally/CA.

Really we could get overly detailed and make it too complicated.

**Comment by jhibbets** [comment]
New version is ready for review

**Comment by jhibbets** [comment]
Final version is ready for your review: https://docs.google.com/document/d/1N1nDvLrKLia2Q9BVEJGx4-Mfufdc28I_ZLDdJRSaF_k/edit#heading=h.gjdgxs

**Comment by ChrisTheDBA** [comment]
That's much more in line with what I have been thinking and two changes:

For brigade sponsor % $1500 - speaker quarterly at $500 - speak once at $150 sponsor the meetup, announced no speak

Sponsorships should be for one year regardless of when you start. So it will include next years TODD event at this time.  It doesn't make sense for someone to jump into to support in the later parts of the year if we reset the clock in January.
