### ISSUE TITLE
Fiscal Sponsor for brigade/CityCamp

### ISSUE THREAD

**Issue by ChrisTheDBA** [codeforraleigh/Captains-Task-List#91]
Is there a better option than CfA

**Comment by ChrisTheDBA** [comment]
So CfA told us today on a call that fiscal sponsorship was being dropped as a service. The explanation , separate accounts and books would need to be kept for each brigade and that was too much work. They will keep collecting donations in our name and sharing the proceeds with us.

**Comment by jhibbets** [comment]
Wow that was one of the biggest benefits for us. Glad we're moving forward
with FI.

**Comment by ChrisTheDBA** [comment]
Getting the details worked out with Jason Widen and Forward Impact. JH and I are in communication.

**Comment by ChrisTheDBA** [comment]
Most of the details have been worked out we submitted two invoices for funds to Rachel on Friday. Fingers crossed.

**Comment by ChrisTheDBA** [comment]
Our sponsor has sent the first invoices for sponsors out. Yea!
